version: '3.8'

services:
  map-my-way:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    container_name: map-my-way
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - tailscale
    labels:
      - "tailscale.serve=map-my-way.tailnet-name.ts.net:3000"
      - "watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
    networks:
      - tailscale

networks:
  tailscale:
    external: true